### ISSUE TITLE
Logs tab crashes on Minikube cluster with error: "Log task finished unexpectedly"

### ISSUE THREAD

**Issue by tqwewe** [grampelberg/kuberift#24]
I've installed kty on my minikube cluster, and ssh'ed into it. However when navigating to the "Logs" tab of a pod, I get an error in the UI which says "Log task finished unexpectedly".

<img width="287" alt="Screenshot 2024-09-25 at 9 44 18 PM" src="https://github.com/user-attachments/assets/3579f1e3-b4e2-412f-8aef-a8331333bdb7">

This also caused my kubectl port forwarding to crash:

```
❯ kubectl -n kty port-forward service/server 2222:2222
Forwarding from 127.0.0.1:2222 -> 2222
Forwarding from [::1]:2222 -> 2222
Handling connection for 2222
E0925 21:44:08.685517   15807 portforward.go:413] an error occurred forwarding 2222 -> 2222: error forwarding port 2222 to pod fb97c9059137cdd5f273d45f0045c1a49b8afc11f3b13ded4e32a721ade8cd48, uid : exit status 1: 2024/09/25 13:44:08 socat[11307] E write(5, 0x556626382000, 68): Broken pipe
error: lost connection to pod
```

This error seems to only happen in some pods. For example, I am able to see logs in the kty server pod running just fine.

**Comment by grampelberg** [comment]
I've seen this with my local `k3d` cluster as well. It seems to have something to do with pods restarting. This is a little better in `main` right now. Instead of the error covering everything up, you see the full logs and a reminder that they're not streaming anymore.

For some reason, k8s is returning all the logs but the stream itself ends. `stern` correctly streams logs still, so I need to go figure out what they're doing differently (and hope that it isn't polling).

Gonna look into this right now.
